# 异常处理

`异常处理(exception handling)`机制允许程序出现问题进行通信并做出相应的处理。

## 抛出异常

在C++语音中，我们通过`抛出(throwing)`一条表达式来引发一个异常。

当执行一个throw时，跟在throw后面的语句将不再被执行。相反，程序的控制权从throw转移到与之匹配的catch模块。这里有两个重要的含义：

+ 函数可能提早退出；
+ 一旦程序开始执行异常处理代码，则沿着调用链创建的对象将被销毁。

### 栈展开

当throw出现在一个try语句块内时，检查与该try块关联的catch子句。

栈展开过程沿着嵌套函数的调用链不断查找，直到找到了与异常匹配的catch子句为止；或者也可能一直没找到匹配的catch，则退出主函数后查找过程终止。

栈展开过程中对象会自动被销毁。

### 析构函数与异常

### 异常对象

`异常对象(exception object)`是一种特殊的对象，编译器使用异常抛出表达式对异常对象进行拷贝初始化。

## 捕获异常

`catch子句(catch clause)`中异常声明看起来像只包含一个形参的函数形参列表。

声明类型决定了处理代码所能捕获的异常类型。这个类型必须是完全类型，它可以是左值引用，但不能是右值引用。

### 重新抛出

一条catch语句通过重新抛出的操作将异常传递给另一个catch语句。这里的重新抛出仍然是一条throw语句，只不过不包含任何表达式。

### 捕获所有异常的处理代码

形如catch(...)，一条语句可以与任意类型的异常匹配。

## noexcept异常说明

在C++11新标准中，我们可以通过提供`noexcept说明`指定某个函数不会抛出异常。

## 参考

+ [C++ Primer](https://zhjwpku.com/assets/pdf/books/C++.Primer.5th.Edition_2013.pdf)